---
- name: Install Kafka dependencies
  apt:
    name:
      - default-jdk
      - zookeeper
      - zookeeperd
    state: present

- name: Download Kafka
  get_url:
    url: "https://www.apache.org/dist/kafka/{{ kafka_version }}/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"

- name: Extract Kafka
  unarchive:
    src: "/tmp/kafka_{{ scala_version }}-{{ kafka_version }}.tgz"
    dest: "/opt/kafka"
    remote_src: yes
    creates: "/opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}"

- name: Configure Kafka
  template:
    src: server.properties.j2
    dest: "/opt/kafka/kafka_{{ scala_version }}-{{ kafka_version }}/config/server.properties"
  notify: restart kafka

- name: Ensure Kafka is running
  script: kafka_startup_script.sh
