---
- name: Setup Monitoring
  hosts: monitoring
  become: yes
  tasks:
    - name: Install Prometheus
      apt:
        name: prometheus
        state: present

    - name: Install Grafana
      apt:
        name: grafana
        state: present

    - name: Install Alertmanager
      apt:
        name: alertmanager
        state: present
        
    notify: restart prometheus, restart grafana, restart alertmanager

  handlers:
    - name: restart prometheus
      service:
        name: prometheus
        state: restarted

    - name: restart grafana
      service:
        name: grafana
        state: restarted

    - name: restart alertmanager
      service:
        name: alertmanager
        state: restarted
