---
- name: Main playbook
  hosts: all
  gather_facts: yes
  become: yes
  tasks:
    - include_playbook: setup_proxmox.yml
    - include_playbook: setup_nginx.yml
    - include_playbook: setup_monitoring.yml
    - include_playbook: setup_kafka.yml
